# Generated by Django 2.2.5 on 2019-11-16 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('image', models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_update_image)),
                ('typeOf', models.CharField(max_length=10)),
                ('organization', models.CharField(blank=True, max_length=80, null=True)),
                ('about', models.CharField(blank=True, max_length=380, null=True)),
                ('pubInterest', models.TextField(blank=True, null=True)),
                ('authInterest', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile post',
                'verbose_name_plural': 'Profile posts',
            },
        ),
    ]
