# Generated by Django 2.2.5 on 2019-11-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favouriteAuthors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
