# Generated by Django 2.2.5 on 2019-11-16 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forum.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('discription', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=forum.models.upload_article_image)),
                ('tags', models.TextField(blank=True, null=True)),
                ('favourites', models.PositiveIntegerField(blank=True, null=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('paperId', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article post',
                'verbose_name_plural': 'Article posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=forum.models.upload_comment_image)),
                ('body', models.TextField()),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment post',
                'verbose_name_plural': 'Comment posts',
            },
        ),
    ]
