# Generated by Django 2.2.1 on 2019-08-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190809_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='favourites',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
