# Generated by Django 2.2.1 on 2019-08-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190809_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
